# Generated by Django 5.2.1 on 2025-05-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер баллона')),
                ('manufacture_year', models.DateField(blank=True, null=True, verbose_name='Год производства')),
                ('status_hydrotesting', models.BooleanField(verbose_name='Гидроиспытание')),
                ('volume', models.PositiveIntegerField(verbose_name='Обьем быллона')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Баллон',
                'verbose_name_plural': 'Баллоны',
            },
        ),
    ]
